---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: whereabouts
  namespace: openshift-multus
  labels:
    tier: node
    app: whereabouts
spec:
  selector:
    matchLabels:
      name: whereabouts
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: whereabouts
        name: whereabouts
    spec:
      hostNetwork: true      
      serviceAccountName: multus
      tolerations:
      - operator: Exists
      containers:
      - name: whereabouts
        image: quay.io/dougbtv/whereabouts:leaderelection
        env:
        - name: SLEEP
          value: "true"
        - name: CNI_CONF_DIR
          value: "/host/etc/kubernetes/cni/net.d"
        - name: CNI_BIN_DIR
          value: "/host/var/lib/cni/bin"
        - name: WHEREABOUTS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/var/lib/cni/bin
        - name: cni-net-dir
          mountPath: /host/etc/kubernetes/cni/net.d
      volumes:
        - name: cnibin
          hostPath:
            path: /var/lib/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/kubernetes/cni/net.d